### ISSUE TITLE
关于仪表盘查询日期

### ISSUE THREAD

**Issue by ChunKitAu** [byteblogs168/plumemo#10]
月：
 DATE_FORMAT(create_time,'%Y-%m-00 00:00:00')
年：
 DATE_FORMAT(create_time,'%Y-01-01 00:00:00')
本月 不是应该 显示天数  年显示月份   你这查询把日 与月都格式了   查询年  全是 20-01-01  20-01-01
数据全去一月份了

还有getBlogsStatistics()函数   如果今天和昨天都是没人访问   获取的数据是空  getDate()时for (AuthUserLogVo userLogVO : todayList)   进不去   返回的ViewTotal都是空

**Comment by byteblogs168** [comment]
这个问题已经修复。
