### ISSUE TITLE
提交封面图成功后，显示问题

### ISSUE THREAD

**Issue by MirKKK** [byteblogs168/plumemo#14]
后台管理系统提交完成，显示
![image](https://user-images.githubusercontent.com/48476676/86919279-91780200-c15a-11ea-871f-e3a23c0dba7c.png)
在plumemo无法显示
![image](https://user-images.githubusercontent.com/48476676/86919404-c08e7380-c15a-11ea-93bd-1bb29b13f075.png)

**Comment by layman-hu** [comment]
有解决方案吗现在

**Comment by byteblogs168** [comment]
请检查自己的图片域名配置，这种情况是你的域名配置有问题
