### ISSUE TITLE
spring-boot-starter-parent版本问题

### ISSUE THREAD

**Issue by DecemberBi** [byteblogs168/plumemo#15]
项目down下来之后，spring-boot-starter-parent坐标的version 2.1.8报红，进入byteblogs-data-boot-starter之后发现依赖的spring-boot-starter-parent是2.2.2。是不是这两个版本冲突导致外层version报红。改为2.2.2之后，不再报红，但还是报No spring.application.name found, defaulting to 'application'，服务没停，也没启动完成，请问这怎么解决，非常感谢
![image](https://user-images.githubusercontent.com/37731138/92309998-96332800-efdc-11ea-9924-9654dbd66d6f.png)

**Comment by byteblogs168** [comment]
已解决
