### ISSUE TITLE
博客还会继续维护更新吗

### ISSUE THREAD

**Issue by loongzcode** [byteblogs168/plumemo#19]
请问博客还会继续维护更新吗？

**Comment by byteblogs168** [comment]
继续维护的，有什么好的建议吗？

**Comment by loongzcode** [comment]
> 继续维护的，有什么好的建议吗？
能加个mysql备份吗，定时任务

**Comment by loongzcode** [comment]
> 继续维护的，有什么好的建议吗？

现在好像没加缓存吧，希望能把分类，标签，访问得多的一些东西加下缓存
