### ISSUE TITLE
项目的数据库表结构能提供吗

### ISSUE THREAD

**Issue by MrPeabodyY** [byteblogs168/plumemo#9]
plumemo后台数据库表结构sql语句能提供一下吗

**Comment by byteblogs168** [comment]
您好这个数据库时自己生成的。可以看这里https://www.plumemo.com/views/question/question.html#_1-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%89%BE%E5%88%B0sql%E6%96%87%E4%BB%B6%EF%BC%9F

**Comment by MrPeabodyY** [comment]
感谢你的回复，项目和代码都很棒（至少看了react和springboot的代码）
我这边还有疑问,本地测试的时候，数据库没测试数据，使用有点懵，最好能提供mysql里的测试数据
而且没找到新增文章的界面和功能，你这个只是博客管理，没有新增博客编辑功能的吗
